esphome:
  name: base
#  platform: ESP8266
#  board: nodemcuv2

# Enable WiFi
wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password
  fast_connect: true

# Enable Home Assistant API
api:
  password: !secret esphome_admin

# Enable logging
logger:

# Enabled OTA
ota:
  password: !secret esphome_ota
